import "./globals.css";
import AppWalletProvider from "./components/AppWalletProvider";


export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};


export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <AppWalletProvider>{children}</AppWalletProvider>
            </body>
        </html>
    );
}
